// Compiles projects/ui/tokens/tokens.json into CSS custom properties.
//
//   primitive  -> :root                      (raw values, never themed)
//   semantic   -> one block per theme        (light is the default, dark also follows prefers-color-scheme)
//   density    -> one block per density
//   component  -> re-declared wherever a theme/density attribute is set, so references re-resolve
//                 inside scoped subtrees (custom properties resolve var() where they are declared).
//
// References like {primitive.color.iris.600} become var(--ui-color-iris-600), so every tier stays
// switchable at runtime without re-rendering Angular components.
//
// Usage: node scripts/build-tokens.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const src = `${root}projects/ui/tokens/tokens.json`;
const out = `${root}projects/ui/styles/tokens.css`;
const tokens = JSON.parse(readFileSync(src, 'utf8'));

/** Flattens nested objects into [['color-iris-600', value], ...]. */
function flatten(obj, prefix = []) {
  return Object.entries(obj).flatMap(([key, value]) =>
    typeof value === 'object' ? flatten(value, [...prefix, key]) : [[[...prefix, key].join('-'), value]],
  );
}

const known = new Set();
for (const [name] of flatten(tokens.primitive)) known.add(`primitive.${name}`);
for (const theme of Object.values(tokens.semantic)) for (const [n] of flatten(theme)) known.add(`semantic.${n}`);
for (const density of Object.values(tokens.density)) for (const [n] of flatten(density)) known.add(`density.${n}`);

function resolve(value, where) {
  return String(value).replace(/\{([^}]+)\}/g, (_, ref) => {
    const [tier, ...rest] = ref.split('.');
    const name = rest.join('-');
    if (!known.has(`${tier}.${name}`)) throw new Error(`Unknown token reference {${ref}} in ${where}`);
    return `var(--ui-${name})`;
  });
}

function block(selector, entries, where, extra = '') {
  const body = entries.map(([name, value]) => `  --ui-${name}: ${resolve(value, where)};`).join('\n');
  return `${selector} {\n${body}${extra}\n}\n`;
}

const themed = (theme) => {
  const entries = flatten(tokens.semantic[theme]);
  const scheme = entries.find(([n]) => n === 'color-scheme')?.[1];
  return [entries, scheme ? `\n  color-scheme: ${scheme};` : ''];
};

const parts = [
  '/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */\n',
  '/* ---- Tier 1: primitive ---- */',
  block(':root', flatten(tokens.primitive).filter(([n]) => n !== '$description'), 'primitive'),
  '/* ---- Tier 2: semantic (themes) ---- */',
  block(":root,\n[data-ui-theme='light']", ...withWhere('light')),
  block("[data-ui-theme='dark']", ...withWhere('dark')),
  `@media (prefers-color-scheme: dark) {\n${indent(block(":root:not([data-ui-theme])", ...withWhere('dark')))}}\n`,
  block("[data-ui-theme='high-contrast']", ...withWhere('high-contrast')),
  '/* ---- Density ---- */',
  block(":root,\n[data-ui-density='comfortable']", flatten(tokens.density.comfortable), 'density.comfortable'),
  block("[data-ui-density='compact']", flatten(tokens.density.compact), 'density.compact'),
  '/* ---- Tier 3: component (re-declared on scoped theme/density roots so references re-resolve) ---- */',
  block(':root,\n[data-ui-theme],\n[data-ui-density]', flatten(tokens.component), 'component'),
];

function withWhere(theme) {
  const [entries, extra] = themed(theme);
  return [entries, `semantic.${theme}`, extra];
}
function indent(text) {
  return text.split('\n').map((l) => (l ? `  ${l}` : l)).join('\n');
}

const css = parts.join('\n');
if (process.argv.includes('--check')) {
  const current = readFileSync(out, 'utf8');
  if (current !== css) {
    console.error('tokens.css is out of date. Run `pnpm tokens`.');
    process.exit(1);
  }
  console.log('tokens.css is up to date.');
} else {
  writeFileSync(out, css);
  console.log(`Wrote ${out.replace(root, '')} (${css.length} bytes)`);
}
